### PR TITLE
Attach docstrings to high level service functions

### PR DESCRIPTION
**Pull request by c42f**
Fixes the second point in #168 which allows users to access the docstrings in the REPL.

I tested this locally in an ad-hoc way by locally modifying deps/metadata.jl and running `julia --project -e 'using AWS; AWS.AWSMetadata.parse_aws_metadata();'`

It seems that the real tests are oddly whitespace insensitive.

### CODE REVIEW

**Comment by mattBrzezinski** [comment]
This is lovely, thanks for the merge request! The tests are whitespace insensitive because I found it to be PITA to modify the tests when whitespace changes really didn't matter.

One test is currently failing locally for me, going to quickly fix that merge it in and then these should be good to go!

**Comment by mattBrzezinski** [comment]
Tested the changes locally to see how the docstrs get generated, look good to me! Thanks again :)

**Comment by c42f** [comment]
Awesome, thanks Matt.

Is there a way to force the whole set of services to get updated? In principle the automated update bot should invalidate the cache based not just on the hashes of the service json definitions, but on the hash of AWSMetadata.jl and AWSMetadataUtilities.jl as well.

**Comment by mattBrzezinski** [comment]
That's one thing which I should have requested to go along side this PR, but I can make a new one for it.
Usually with breaking changes, I would regenerate all service definitions by wiping the `deps/metadata.json` file to just `{}`. This would force everything to be re-created.

We could modify the bot to just ignore the contents of the `deps/metadata.json` file, and just re-generate all definitions. This would definitely increase the runtime but when the merge request is made you'd always have the proper version. I guess runtime complexity doesn't matter much in this case.

I've logged an issue for this change https://github.com/JuliaCloud/AWS.jl/issues/234, thanks for bringing it up. It's definitely a change which makes sense to have!

**Pull request merged**
