### PR TITLE
read_iam_credentials if no other credentials are given

### PR DESCRIPTION
**Pull request by gustafsson**
From within an EC2 node we can access temporary AWS credentials through the IAM profile.

### CODE REVIEW

**Comment by gustafsson** [comment]
For reference, I think this is similar to how s3cmd implemented this logic https://github.com/s3tools/s3cmd/blob/333bb792d7488b0d87cfa3e9998be21f7d6f4a40/S3/Config.py#L210

**Comment by tanmaykm** [comment]
Thanks @gustafsson 

But isn't this the same as what has been implemented [here](https://github.com/JuliaCloud/AWS.jl/blob/4ca32795fb3e7d4a98f9b4299963fff9c65192a4/src/AWS.jl#L190-L217)?

**Comment by gustafsson** [comment]
Ups, I missed that

**Comment by tanmaykm** [comment]
okay. will close this as it is already available.

**Comment by gustafsson** [comment]
Thanks

**Pull request closed without merging**
