### PR TITLE
Fix `aws_get_profile_settings` when profile is missing

### PR DESCRIPTION
**Pull request by omus**
Bug introduced in #357

### CODE REVIEW

**Comment by omus** [comment]
bors try

**Review by mattBrzezinski — APPROVED** [review]
LGTM!

**Comment by nickrobinson251** [comment]
I believe this PR just moved the issue down one step?

Before (on v1.60.0), the error i see is:
```julia
ERROR: LoadError: InitError: MethodError: no method matching length(::Nothing)
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at abstractdict.jl:58
  length(::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/adjtrans.jl:195
  length(::Union{IterTools.Properties, IterTools.PropertyValues}) at /Users/admin/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/IterTools/0dYLc/src/IterTools.jl:1003
  ...
Stacktrace:
  [1] Dict{String, String}(kv::Nothing)
    @ Base ./dict.jl:102
  [2] aws_get_profile_settings
    @ ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/ht8eI/src/AWSCredentials.jl:582 [inlined]
  [3] _aws_get_role(role::String, ini::IniFile.Inifile)
    @ AWS ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/ht8eI/src/utilities/credentials.jl:63
  [4] dot_aws_config(profile::String)
    @ AWS ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/ht8eI/src/AWSCredentials.jl:414
  [5] (::AWS.var"#8#12"{String})()
    @ AWS ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/ht8eI/src/AWSCredentials.jl:117
  [6] AWS.AWSCredentials(; profile::Nothing, throw_cred_error::Bool)
    @ AWS ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/ht8eI/src/AWSCredentials.jl:126
  [7] AWS.AWSConfig()
    @ AWS ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/ht8eI/src/AWSConfig.jl:14
  [8] #global_aws_config#49
    @ ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/ht8eI/src/AWS.jl:58 [inlined]
  [9] global_aws_config
    @ ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/ht8eI/src/AWS.jl:57 [inlined]
```
Now (on v1.60.1), i see:
```julia
ERROR: LoadError: InitError: MethodError: no method matching get(::Nothing, ::String, ::Nothing)
Closest candidates are:
  get(::CategoricalArrays.CategoricalPool, ::Any, ::Any) at /Users/admin/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/CategoricalArrays/rDwMt/src/pool.jl:55
  get(::DataStructures.PriorityQueue, ::Any, ::Any) at /Users/admin/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/DataStructures/nBjdy/src/priorityqueue.jl:176
  get(::WeakKeyDict{K, V} where V, ::Any, ::Any) where K at weakkeydict.jl:140
  ...
Stacktrace:
  [1] _aws_get_role(role::String, ini::IniFile.Inifile)
    @ AWS ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/dceAr/src/utilities/credentials.jl:64
  [2] dot_aws_config(profile::String)
    @ AWS ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/dceAr/src/AWSCredentials.jl:414
  [3] (::AWS.var"#8#12"{String})()
    @ AWS ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/dceAr/src/AWSCredentials.jl:117
  [4] AWS.AWSCredentials(; profile::Nothing, throw_cred_error::Bool)
    @ AWS ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/dceAr/src/AWSCredentials.jl:126
  [5] AWS.AWSConfig()
    @ AWS ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/dceAr/src/AWSConfig.jl:14
  [6] #global_aws_config#49
    @ ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/dceAr/src/AWS.jl:58 [inlined]
  [7] global_aws_config
    @ ~/builds/f75a2375/0/invenia/research/DataSoupParsers.jl.tmp/depot/packages/AWS/dceAr/src/AWS.jl:57 [inlined]
```
i.e. `_aws_get_role` does not handle `aws_get_profile_settings(role, ini) == nothing`

**Pull request merged**
