### PR TITLE
Overwrite using `withenv` instead of `ENV`

### PR DESCRIPTION
**Pull request by omus**
Best to use `withenv` instead of overwriting environmental variables with `ENV` as otherwise changes persist beyond the scope of the testset.

### CODE REVIEW

**Comment by omus** [comment]
bors try

**Review by mattBrzezinski — APPROVED** [review]
LGTM, feel free to kick `bors` whenever!

**Comment by omus** [comment]
Seems to be a random failure:
```
<?xml version="1.0" encoding="UTF-8"?>
  <Error><Code>TooManyBuckets</Code><Message>You have attempted to create more buckets than allowed</Message><CurrentNumberOfBuckets>101</CurrentNumberOfBuckets><AllowedNumberOfBuckets>101</AllowedNumberOfBuckets><RequestId>AKF82E0NJDDVDK75</RequestId><HostId>ad8QNClLI4wqGlLeYxpSK5WqY2UnJrYRfPEdOAAqJZNDWl4FZ4fVTTVX+tRb1rgwoY7mtKip3yk=</HostId></Error>
```

**Comment by mattBrzezinski** [comment]
> Seems to be a random failure:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
>   <Error><Code>TooManyBuckets</Code><Message>You have attempted to create more buckets than allowed</Message><CurrentNumberOfBuckets>101</CurrentNumberOfBuckets><AllowedNumberOfBuckets>101</AllowedNumberOfBuckets><RequestId>AKF82E0NJDDVDK75</RequestId><HostId>ad8QNClLI4wqGlLeYxpSK5WqY2UnJrYRfPEdOAAqJZNDWl4FZ4fVTTVX+tRb1rgwoY7mtKip3yk=</HostId></Error>
> ```

Oh yay... something w/ CI failing isn't cleaning buckets properly. I'll empty the account in a bit!

**Comment by mattBrzezinski** [comment]
@omus just cleaned out the S3 buckets in the AWS account. I'll keep an eye out on lingering buckets, and look through the test code to try and track down where we're missing a `try/finally`.

**Pull request merged**
