### PR TITLE
Raised compat of OrderedCollections.

### LINKED ISSUE #505: Signing is broken for OrderedCollections 1.2.0 and older
When downloading data from S3-like storage and using `OrdredCollections@1.2.0`  or older, following exception is raised:
```julia
ERROR: LoadError: type KeyError has no field code
Stacktrace:
 [1] getproperty(::KeyError, ::Symbol) at .\Base.jl:33
 [2] macro expansion at C:\Users\racinsky\.julia\packages\Retry\vS1bg\src\repeat_try.jl:110 [inlined]
 [3] submit_request(::HcpConfig, ::Request; return_headers::Nothing) at C:\Users\racinsky\.julia\packages\AWS\nUGJF\src\utilities\request.jl:85
 [4] (::RestXMLService)(::String, ::String, ::Dict{String,Any}; aws_config::HcpConfig, feature_set::AWS.FeatureSet) at C:\Users\racinsky\.julia\packages\AWS\nUGJF\src\AWS.jl:284
 [5] #get_object#89 at C:\Users\racinsky\.julia\packages\AWS\nUGJF\src\services\s3.jl:2591 [inlined]
 [6] top-level scope at c:\Projects\something\aws_jl_problem\older\main.jl:41
in expression starting at c:\Projects\something\aws_jl_problem\older\main.jl:41

caused by: KeyError: key "Authorization" not found
Stacktrace:
 [1] pop!(::LittleDict{String,String,Array{String,1},Array{String,1}}, ::String) at C:\Users\racinsky\.julia\packages\OrderedCollections\P6ntV\src\little_dict.jl:244
 [2] delete!(::LittleDict{String,String,Array{String,1},Array{String,1}}, ::String) at C:\Users\racinsky\.julia\packages\OrderedCollections\P6ntV\src\little_dict.jl:248
 [3] sign_aws4!(::HcpConfig, ::Request, ::Dates.DateTime) at C:\Users\racinsky\.julia\packages\AWS\nUGJF\src\utilities\sign.jl:70
 [4] sign!(::HcpConfig, ::Request; time::Dates.DateTime) at C:\Users\racinsky\.julia\packages\AWS\nUGJF\src\utilities\sign.jl:5
 [5] sign! at C:\Users\racinsky\.julia\packages\AWS\nUGJF\src\utilities\sign.jl:2 [inlined]    
 [6] macro expansion at C:\Users\racinsky\.julia\packages\AWS\nUGJF\src\utilities\request.jl:86 [inlined]
 [7] macro expansion at C:\Users\racinsky\.julia\packages\Retry\vS1bg\src\repeat_try.jl:192 [inlined]
 [8] submit_request(::HcpConfig, ::Request; return_headers::Nothing) at C:\Users\racinsky\.julia\packages\AWS\nUGJF\src\utilities\request.jl:85
 [9] (::RestXMLService)(::String, ::String, ::Dict{String,Any}; aws_config::HcpConfig, feature_set::AWS.FeatureSet) at C:\Users\racinsky\.julia\packages\AWS\nUGJF\src\AWS.jl:284
 [10] #get_object#89 at C:\Users\racinsky\.julia\packages\AWS\nUGJF\src\services\s3.jl:2591 [inlined]
 [11] top-level scope at c:\Projects\something\aws_jl_problem\older\main.jl:41
```
the MWE is here. We are using S3-compatible Hitachi Content platform, so these are wrappers for it:
```julia
using AWS
AWS.@service S3
struct HcpConfig <: AbstractAWSConfig
   endpoint::String
   region::String
   creds
end
AWS.region(c::HcpConfig) = c.region
AWS.credentials(c::HcpConfig) = c.creds

struct HcpCredentials
    access_key_id::String
    secret_key::String
    token::String
    HcpCredentials(access_key_id,secret_key) = new(access_key_id,secret_key,"")
end

AWS.check_credentials(c::HcpCredentials) = c
function AWS.generate_service_url(aws::HcpConfig, service::String, resource::String)
    service == "s3" || throw(ArgumentError("Can only handle s3 requests to HCP"))
    return "$(aws.endpoint)$resource"
end

# so credentials lod during init in container in kubernetes with correct env vars
aws_config = HcpConfig("secret", "", HcpCredentials("secret", "secret"))

function split_url(url)
    m = match(r"s3:\/\/([^/]*)\/(.*)", url)
    m[1], m[2]
end

bucket, path = split_url("s3://mlflow-artifacts-stage/28/3b087653719d4db5b7a33895cc5ce9cd/artifacts/model.bson.gz")
ModelTools.S3.get_object(bucket, path; aws_config)
```

packages are:
```julia
(older) pkg> st
Status `C:\Projects\something\aws_jl_problem\older\Project.toml`
  [fbe9abb3] AWS v1.68.0
  [bac558e1] OrderedCollections v1.2.0
```

this is because this is called:
https://github.com/JuliaCloud/AWS.jl/blob/v1.68.0/src/utilities/sign.jl#L70
and that calls https://github.com/JuliaCollections/OrderedCollections.jl/blob/v1.2.0/src/little_dict.jl#L231-L245
which has `throw(KeyError(key))` in the end.
The information that `Authorization` header should be mandatory is nowhere to be found.

With newer `OrderedCollections` this does not happen, because in next version the error raising is removed. 
But the current compat is https://github.com/JuliaCloud/AWS.jl/blob/v1.68.0/Project.toml#L32
so it allows using this older version where this is broken.
Should we require OrderedCollections@1.3 and higher?

### PR DESCRIPTION
**Pull request by racinmat**
Fixes #505 .
I hope this should not restrict versions too much, `OrderedCollections@1.3.0` were released in Jul 2, 2020, so that's still already quite old.

### CODE REVIEW

**Comment by ericphanson** [comment]
The syntax `OrderedCollections = "1"` means “all versions of OrderedCollections semver compatible with v1”, which means anything less anything after (or including) v2 and before v2. (See https://pkgdocs.julialang.org/v1/compatibility/#Version-specifier-format). In other words, this PR reduces the range versions AWS is compatible with (new minimum of v1.3) instead of expanding it.

**Comment by racinmat** [comment]
I know it reduces range of version, that's the purpose. See #505 , that's why I want to exclude the version 1.2.0 and older, because the code ia broken there.

**Comment by ericphanson** [comment]
Oops, missed that!

**Review by omus — APPROVED** [review]

**Pull request merged**
