### PR TITLE
NFC: Reorganized source tree

### PR DESCRIPTION
**Pull request by mattBrzezinski**
## Overview
The `src/AWS.jl` file and `src/AWSCredentials.jl` files were quite long and difficult to read and follow. I've created a new sub-directory `src/utilities/` and moved internal functions from various places into their respective files.

### CODE REVIEW

**Comment by mattBrzezinski** [comment]
bors try

**Comment by iamed2** [comment]
Feels weird to me that the API Generation utilities isn't in the same directory tree as the API Generation code. I feel like it should be `src/api_generation/utilities.jl` or `src/api_generation/utilities/utilities.jl` or something.

**Comment by mattBrzezinski** [comment]
> Feels weird to me that the API Generation utilities isn't in the same directory tree as the API Generation code. I feel like it should be `src/api_generation/utilities.jl` or `src/api_generation/utilities/utilities.jl` or something.

I originally thought of this, and went this route instead. I'll swap it over, I'm 50/50 on it.

**Review by iamed2 — APPROVED** [review]

**Comment by mattBrzezinski** [comment]
bors cancel

**Pull request merged**
