### PR TITLE
Ability to perform unsigned requests

### PR DESCRIPTION
**Pull request by mattBrzezinski**
Resolves: #227 

TODO: Update to point at `master` after #226 is merged in. Just doing this now since I based the moving of files and functions around in there here.

### CODE REVIEW

**Review by mjram0s — APPROVED** [review]

**Comment by mattBrzezinski** [comment]
bors try

**Comment by mattBrzezinski** [comment]
bors cancel

**Comment by mattBrzezinski** [comment]
bors try

**Comment by mattBrzezinski** [comment]
bors cancel

**Comment by mattBrzezinski** [comment]
bors try-

**Comment by mattBrzezinski** [comment]
bors try

**Comment by mattBrzezinski** [comment]
bors try-

**Comment by mattBrzezinski** [comment]
bors try

**Comment by mattBrzezinski** [comment]
bors try

**Review by iamed2 — APPROVED** [review]

**Pull request merged**
