### PR TITLE
Retry certain errors more times

### LINKED ISSUE #541: Missing retry for "resolve host" error with Downloads backend?
Just got this error on two workers (different keys, same bucket) at about the same time:
```julia
ERROR: LoadError: Could not resolve host: s3.us-east-2.amazonaws.com while requesting https://s3.us-east-2.amazonaws.com/MY_BUCKET/MY_KEY
Stacktrace:
  [1] (::Downloads.var"#9#18"{Base.BufferStream, Base.DevNull, String, OrderedCollections.LittleDict{String, String, Vector{String}, Vector{String}}, Float64, Nothing, Bool, Bool, String, Int64, Bool, Bool})(easy::Downloads.Curl.Easy)
    @ Downloads /usr/local/julia/share/julia/stdlib/v1.7/Downloads/src/Downloads.jl:369
  [2] with_handle(f::Downloads.var"#9#18"{Base.BufferStream, Base.DevNull, String, OrderedCollections.LittleDict{String, String, Vector{String}, Vector{String}}, Float64, Nothing, Bool, Bool, String, Int64, Bool, Bool}, handle::Downloads.Curl.Easy)
    @ Downloads.Curl /usr/local/julia/share/julia/stdlib/v1.7/Downloads/src/Curl/Curl.jl:64
  [3] #8
    @ /usr/local/julia/share/julia/stdlib/v1.7/Downloads/src/Downloads.jl:311 [inlined]
  [4] arg_write(f::Downloads.var"#8#17"{Base.DevNull, String, OrderedCollections.LittleDict{String, String, Vector{String}, Vector{String}}, Float64, Nothing, Bool, Bool, String, Int64, Bool, Bool}, arg::Base.BufferStream)
    @ ArgTools /usr/local/julia/share/julia/stdlib/v1.7/ArgTools/src/ArgTools.jl:112
  [5] #7
    @ /usr/local/julia/share/julia/stdlib/v1.7/Downloads/src/Downloads.jl:310 [inlined]
  [6] arg_read
    @ /usr/local/julia/share/julia/stdlib/v1.7/ArgTools/src/ArgTools.jl:61 [inlined]
  [7] request(url::String; input::Nothing, output::Base.BufferStream, method::String, headers::OrderedCollections.LittleDict{String, String, Vector{String}, Vector{String}}, timeout::Float64, progress::Nothing, verbose::Bool, throw::Bool, downloader::Downloads.Downloader)
    @ Downloads /usr/local/julia/share/julia/stdlib/v1.7/Downloads/src/Downloads.jl:309
  [8] macro expansion
    @ ~/.julia/packages/Mocking/MsKoy/src/mock.jl:29 [inlined]
  [9] macro expansion
    @ ~/.julia/packages/AWS/5goc1/src/utilities/downloads_backend.jl:72 [inlined]
 [10] macro expansion
    @ ~/.julia/packages/Retry/vS1bg/src/repeat_try.jl:192 [inlined]
 [11] _http_request(backend::AWS.DownloadsBackend, request::AWS.Request, response_stream::IOBuffer)
...
```
This is with code that just executed several thousand times as part of the same job over the past few days without issue.

### LINKED ISSUE #542: Increase number of retries for 500 errors?
I had a long running job go down with
```julia
HTTP.ExceptionRequest.StatusError(500, "GET", "/bucket/key", HTTP.Messages.Response:
    """
    HTTP/1.1 500 Internal Server Error
    x-amz-request-id: 9E4ZYFR318DFC20R
    x-amz-id-2: ftAYyOnFknM17wNC+01olBbN8Gj7O1vY7FdIQ6Ap/tF2ge2ndN5waZzu12+QyLtaqM1/2YQ70GU=
    content-type: application/xml
    transfer-encoding: chunked
    date: Sun, 17 Apr 2022 04:51:19 GMT
    server: AmazonS3
    connection: close
    
    [Message Body was streamed]""")
    
    <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>9E4ZYFR318DFC20R</RequestId><HostId>ftAYyOnFknM17wNC+01olBbN8Gj7O1vY7FdIQ6Ap/tF2ge2ndN5waZzu12+QyLtaqM1/2YQ70GU=</HostId></Error>
    
    Stacktrace:
      [1] _http_response(req::Request, res::Downloads.Response; throw::Bool)
        @ AWS ~/.julia/packages/AWS/5goc1/src/utilities/downloads_backend.jl:111
      [2] macro expansion
        @ ~/.julia/packages/AWS/5goc1/src/utilities/downloads_backend.jl:85 [inlined]
      [3] macro expansion
        @ ~/.julia/packages/Retry/vS1bg/src/repeat_try.jl:192 [inlined]
      [4] _http_request(backend::AWS.DownloadsBackend, request::Request, response_stream::IOBuffer)
        @ AWS ~/.julia/packages/AWS/5goc1/src/utilities/downloads_backend.jl:63
      [5] macro expansion
        @ ~/.julia/packages/Mocking/MsKoy/src/mock.jl:29 [inlined]
      [6] macro expansion
        @ ~/.julia/packages/AWS/5goc1/src/utilities/request.jl:88 [inlined]
      [7] macro expansion
        @ ~/.julia/packages/Retry/vS1bg/src/repeat_try.jl:192 [inlined]
      [8] submit_request(aws::AWSConfig, request::Request; return_headers::Nothing)
        @ AWS ~/.julia/packages/AWS/5goc1/src/utilities/request.jl:85
      [9] (::RestXMLService)(request_method::String, request_uri::String, args::OrderedCollections.LittleDict{String, Any, Vector{String}, Vector{Any}}; aws_config::AWSConfig, feature_set::AWS.FeatureSet)
        @ AWS ~/.julia/packages/AWS/5goc1/src/AWS.jl:284
     [10] #get_object#90
```
I believe we do do an exponential backoff retry up to 4 times in this case: https://cs.github.com/JuliaCloud/AWS.jl/blob/bf568c348060c6151faf5741550c84b06be42732/src/utilities/downloads_backend.jl#L105.

However the fact that I'm seeing this error from s3 means maybe we should retry more? For me, I'd rather it take a few minutes to get this data from s3 than for the job to crash (on a weekend even!).

### PR DESCRIPTION
**Pull request by ericphanson**
Closes #542
Closes #541

### CODE REVIEW

**Comment by mattBrzezinski** [comment]
Mind just version bumping in here?

**Review by mattBrzezinski — APPROVED** [review]

**Comment by ericphanson** [comment]
Bumped!

**Comment by ericphanson** [comment]
bors merge

**Comment by ericphanson** [comment]
Ahh, we are relying on exceeding the number of retries in some tests, I think. I'll have to update them.

**Comment by ericphanson** [comment]
I think maybe that was it; let's see if it goes through:

bors r+

**Comment by mattBrzezinski** [comment]
Updated you to an admin, should fix your perms 🤷

**Comment by ericphanson** [comment]
Hm, it says the build was cancelled; not really sure how that can happen

**Comment by ericphanson** [comment]
Going to just try again

bors r+

**Comment by ericphanson** [comment]
Cancelled again 🤔

**Comment by ericphanson** [comment]
bors try

**Comment by ericphanson** [comment]
Oh! I know what's happening. It is reaching the 30 minute timeout and being cancelled. So it is likely a problem in the code, not a bors problem.

**Comment by ericphanson** [comment]
I wonder if Retry.jl's exponential delays just become too huge 😂

**Comment by ericphanson** [comment]
Closing in favor of https://github.com/JuliaCloud/AWS.jl/pull/550

**Pull request closed without merging**
