### PR TITLE
Re-enable Auto Generation

### PR DESCRIPTION
**Pull request by mattBrzezinski**

### CODE REVIEW

**Comment by mattBrzezinski** [comment]
bors try

**Comment by mattBrzezinski** [comment]
bors try

**Comment by mattBrzezinski** [comment]
bors cancel

**Comment by mattBrzezinski** [comment]
bors try-

**Comment by mattBrzezinski** [comment]
bors try

**Comment by mattBrzezinski** [comment]
Migrated from TravisCI.org to TravisCI.com, this needed new keys to be encrypted hence the change there.

**Review by mjram0s — APPROVED** [review]

**Pull request merged**
