### PR TITLE
Enable non-AWS S3 service providers

### PR DESCRIPTION
**Pull request by mattBrzezinski**
Resolves: #111 

## Problem
One thing which I overlooked when creating this package was using different S3 service providers for backed storage. If you currently use a different service provider, the S3 functionality will not work.

## Solution
Pass in an arg when making an `S3` request called `service_host` to generate the URL properly.

```julia
args = Dict("service_host"=>"my_user_host")
result = s3("GET", "my-bucket", args)
```

### CODE REVIEW

**Comment by iamed2** [comment]
I propose moving this into all the service types and making `service_host` a required argument for `_generate_service_url`. My reasoning is that this can be used to support AWS in China, which we currently do not support. The domain for the aws-cn partition is `amazonaws.cn`.

**Comment by iamed2** [comment]
There seems to be some clock skew in one of the macOS jobs:

https://travis-ci.com/github/JuliaCloud/AWS.jl/jobs/395211708

```
  AWSException("RequestTimeTooSkewed", "The difference between the request time and the current time is too large.", EzXML.Document(EzXML.Node(<DOCUMENT_NODE@0x00007fdd9ffd3f80>)), HTTP.ExceptionRequest.StatusError(403, "PUT", "/aws-jl-test---20201005t160801040z", HTTP.Messages.Response:  """
  HTTP/1.1 403 Forbidden
  x-amz-request-id: 8B8EE335D4644D8F
  x-amz-id-2: APDfgIBUgSpQpY3kFB+dtjliE/TV6h6I6O+W5KI+gcY+2FXH4EqX1zZnxfOWxv0PKLh9IlpaVN4=
  Content-Type: application/xml
  Transfer-Encoding: chunked
  Date: Mon, 05 Oct 2020 15:28:32 GMT
  Server: AmazonS3
  
  <?xml version="1.0" encoding="UTF-8"?>
  <Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><RequestTime>20201005T160803Z</RequestTime><ServerTime>2020-10-05T15:28:33Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>8B8EE335D4644D8F</RequestId><HostId>APDfgIBUgSpQpY3kFB+dtjliE/TV6h6I6O+W5KI+gcY+2FXH4EqX1zZnxfOWxv0PKLh9IlpaVN4=</HostId></Error>"""))
```

**Comment by iamed2** [comment]
A rerun did not have the clock skew issue.

**Comment by mattBrzezinski** [comment]
> There seems to be some clock skew in one of the macOS jobs:
> 
> https://travis-ci.com/github/JuliaCloud/AWS.jl/jobs/395211708

https://github.com/JuliaCloud/AWS.jl/issues/206

**Comment by mattBrzezinski** [comment]
> I propose moving this into all the service types and making `service_host` a required argument for `_generate_service_url`. My reasoning is that this can be used to support AWS in China, which we currently do not support. The domain for the aws-cn partition is `amazonaws.cn`.

Sure, can do!

**Comment by mattBrzezinski** [comment]
LittleDict does not have a `pop!` with a default value currently, just waiting on:

> https://github.com/JuliaCollections/OrderedCollections.jl/pull/59

**Comment by mattBrzezinski** [comment]
Closing in favour of #211

**Comment by iamed2** [comment]
@mattBrzezinski you closed this in favour of itself 😕

**Comment by mattBrzezinski** [comment]
Resolved in https://github.com/JuliaCloud/AWS.jl/pull/274

**Pull request closed without merging**
