### PR TITLE
Early exit if profile settings are nothing

### PR DESCRIPTION
**Pull request by mattBrzezinski**
Still seeing an [issue](https://github.com/JuliaCloud/AWS.jl/pull/446#issuecomment-916778516) with the recent changes to AWSCredentials.

### CODE REVIEW

**Review by omus — COMMENTED** [review]
Lets add some small test for this like was done in #446. Otherwise looks good

**Comment by omus** [comment]
@nickrobinson251 can you confirm that your code works with this branch?

**Comment by mattBrzezinski** [comment]
> Lets add some small test for this like was done in #446. Otherwise looks good

Added a couple small unit tests. Will add some more testing at some point. Probably should run CodeCoverage here and see where we're at.

**Review by omus — APPROVED** [review]

**Comment by omus** [comment]
bors try

**Comment by nickrobinson251** [comment]
thanks!

**Pull request merged**
